# config/__init__.py
"""
설정 패키지 초기화
"""
from .settings import (
    ROOT_DIR, DATA_DIR, IMAGES_DIR, JSON_DIR, CHECKPOINT_DIR,
    NAVER_CLIENT_ID, NAVER_CLIENT_SECRET, DB_TYPE, DATABASE_URL,
    MAX_RETRIES, REQUEST_DELAY, MAX_PAGES_PER_KEYWORD, DAILY_API_LIMIT,
    CHECKPOINT_INTERVAL, LOG_LEVEL, LOG_FILE, LOG_LEVEL_MAP,
    MEDICINE_PATTERNS, SEARCH_DEFAULTS, MEDICINE_SECTIONS, MEDICINE_PROFILE_ITEMS,
    MEDICINE_SCHEMA
)
